# Generated by Django 5.2.1 on 2025-06-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_accident_detected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='delete_by',
        ),
    ]
