# Generated by Django 5.2.1 on 2025-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_accident_delete_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='snapshot',
            field=models.ImageField(upload_to='accidents/snapshot/'),
        ),
    ]
